---
engines:
  duplication:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: false
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.rb"
  - "_sass/**/*.scss"
exclude_paths: []
